"""Initial migration

Revision ID: 75d17d60b8db
Revises: 
Create Date: 2024-11-03 11:41:08.217433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75d17d60b8db"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("info", sa.String(length=10000), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("balance", sa.Integer(), nullable=True),
        sa.Column("sum_donations", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("next_update", sa.DateTime(), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("n_errors", sa.Integer(), nullable=True),
        sa.Column("n_mints", sa.Integer(), nullable=True),
        sa.Column("n_melts", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_mints_id"), "mints", ["id"], unique=False)
    op.create_table(
        "swaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_id", sa.Integer(), nullable=True),
        sa.Column("to_id", sa.Integer(), nullable=True),
        sa.Column("from_url", sa.String(), nullable=True),
        sa.Column("to_url", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("fee", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("time_taken", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("error", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["mints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_url"],
            ["mints.url"],
        ),
        sa.ForeignKeyConstraint(
            ["to_id"],
            ["mints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_url"],
            ["mints.url"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_swaps_id"), "swaps", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_swaps_id"), table_name="swaps")
    op.drop_table("swaps")
    op.drop_index(op.f("ix_mints_id"), table_name="mints")
    op.drop_table("mints")
    # ### end Alembic commands ###
