"""Add error to SwapEvent

Revision ID: ff1081bcc32e
Revises: 628b6566aa67
Create Date: 2024-10-08 21:07:32.262589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1081bcc32e'
down_revision: Union[str, None] = '628b6566aa67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('error', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'error')
    # ### end Alembic commands ###
